#!/bin/bash
# Translate Chinese in documents.py using line-based sed (safe, no duplication)
set -e
cd /home/hongb/.openclaw/workspace/filebot/backend

FILE="app/routers/documents.py"
echo "Starting translation of $FILE..."

# ============== DOCSTRINGS ==============

# === Permission/access check helpers ===
sed -i 's/^# ========== 权限检查辅助函数 ==========/# ========== Permission Check Helpers ==========/' "$FILE"
sed -i 's/"""检查用户是否有权限访问文件夹/"""Check user permission to access a folder/' "$FILE"
sed -i 's/folder_id: 文件夹ID/folder_id: folder ID/' "$FILE"
sed -i 's/current_user: 当前用户/current_user: current user/' "$FILE"
sed -i 's/db: 数据库会话/db: database session/' "$FILE"
sed -i 's/require_owner: 是否要求用户必须是文件夹的所有者（应用所有者）/require_owner: whether user must be folder owner (app owner)/' "$FILE"
sed -i 's/Folder对象（如果权限检查通过）/Folder object (if permission check passes)/' "$FILE"
sed -i 's/HTTPException: 如果文件夹不存在或用户没有权限/HTTPException: if folder not found or user lacks permission/' "$FILE"

# === Inline comments ===
sed -i 's/# 将UUID转换为字符串进行查询/# Convert UUID to string for querying/' "$FILE"
sed -i 's/# 超级用户可以访问所有资源/# Superuser can access all resources/' "$FILE"
sed -i 's/detail="文件夹不存在"/detail="Folder not found"/' "$FILE"
sed -i 's/# 获取文件夹及其关联的应用/# Get folder and its associated app/' "$FILE"
sed -i 's/detail="没有权限访问此文件夹"/detail="No permission to access this folder"/' "$FILE"
sed -i 's/# 如果要求所有者，确保用户是应用所有者/# If require_owner, ensure user is app owner/' "$FILE"
sed -i 's/detail="只有所有者才能执行此操作"/detail="Only the owner can perform this operation"/' "$FILE"

# === get_folder_by_id_or_path ===
sed -i 's/"""通过ID或路径获取文件夹并进行权限检查（路径优先）/"""Get folder by ID or path with permission check (path-first)/' "$FILE"
sed -i 's/folder_identifier: 文件夹路径（如/folder_identifier: folder path (e.g./' "$FILE"
sed -i 's/）或UUID（已弃用/) or UUID (deprecated)/' "$FILE"
sed -i 's/create_if_not_exists: 如果文件夹不存在，是否自动创建/create_if_not_exists: auto-create folder if not found/' "$FILE"
sed -i 's/注意：建议使用路径标识符，UUID支持已弃用/Note: path identifiers recommended, UUID support deprecated/' "$FILE"

# Comments in get_folder_by_id_or_path
sed -i 's/# 优先按路径查找（路径优先策略）/# Priority: lookup by path (path-first strategy)/' "$FILE"
sed -i 's/# 检查是否是路径格式（以\/开头）/# Check if path format (starts with \//' "$FILE"
sed -i 's/# 直接按路径查找/# Direct path lookup/' "$FILE"
sed -i 's/logger\.info(f"✅ 通过路径找到文件夹: /logger.info(f"Found folder by path: /' "$FILE"
sed -i 's/# 可能是UUID或编码路径/# Could be UUID or encoded path/' "$FILE"
sed -i 's/# 先尝试按路径查找（可能传入的是编码路径）/# Try path lookup first (might be encoded path)/' "$FILE"
sed -i 's/logger\.info(f"✅ 通过解码路径找到文件夹: /logger.info(f"Found folder by decoded path: /' "$FILE"
sed -i 's/(原始: /(original: /' "$FILE"
sed -i 's/# 如果没找到，尝试按UUID查找（向后兼容）/# If not found, try UUID lookup (backward compatible)/' "$FILE"
sed -i 's/# 检查是否是UUID格式/# Check if UUID format/' "$FILE"
sed -i 's/logger\.warning(f"⚠️  通过UUID找到文件夹: /logger.warning(f"Found folder by UUID: /' "$FILE"
sed -i 's/(路径: /(path: /' "$FILE"
sed -i 's/# 既不是路径也不是UUID，尝试作为路径处理（添加\/前缀）/# Neither path nor UUID, try as path (add \/ prefix)/' "$FILE"
sed -i 's/logger\.info(f"✅ 通过添加\/前缀找到文件夹: /logger.info(f"Found folder by adding \/ prefix: /' "$FILE"
sed -i 's/# 如果文件夹不存在且允许创建/# If folder not found and auto-create allowed/' "$FILE"
sed -i 's/# 使用folder_identifier作为路径（可能已经添加了\/前缀）/# Use folder_identifier as path (may have \/ prefix already)/' "$FILE"
sed -i 's/# 解析路径：格式为 \/app-slug\/folder-path/# Parse path: format \/app-slug\/folder-path/' "$FILE"
sed -i 's/detail="路径格式无效，应为 \/app-slug\/folder-path"/detail="Invalid path format, must be \/app-slug\/folder-path"/' "$FILE"
sed -i 's/# 查找应用/# Find app/' "$FILE"
sed -i 's/detail=f"应用 '\''{app_slug}'\'' 不存在"/detail=f"App '\''{app_slug}'\'' not found"/' "$FILE"
sed -i 's/# 检查应用权限（超级用户可以跳过）/# Check app permission (superuser can bypass)/' "$FILE"
sed -i 's/detail="没有权限在此应用中创建文件夹"/detail="No permission to create folder in this app"/' "$FILE"
sed -i 's/# 递归创建文件夹和所有父文件夹/# Recursively create folders and parents/' "$FILE"
sed -i 's/# 检查文件夹是否已存在/# Check if folder already exists/' "$FILE"
sed -i 's/# 创建新文件夹/# Create new folder/' "$FILE"
sed -i 's/print(f"已创建文件夹: /print(f"Created folder: /' "$FILE"
sed -i 's/# 重新加载关联的应用对象/# Reload associated app object/' "$FILE"
sed -i 's/# 如果文件夹仍然不存在（且不允许创建）/# If folder still not found (and cannot create)/' "$FILE"
sed -i 's/# 检查应用权限/# Check app permission/' "$FILE"
sed -i 's/folder_identifier: 文件夹路径（如/folder_identifier: folder path (e.g./' "$FILE"

# === check_document_access ===
sed -i 's/"""检查用户是否有权限访问文档/"""Check user permission to access a document/' "$FILE"
sed -i 's/document_id: 文档ID/document_id: document ID/' "$FILE"
sed -i 's/require_owner: 是否要求用户必须是文档的所有者（应用所有者）/require_owner: whether user must be document owner (app owner)/' "$FILE"
sed -i 's/Document对象（如果权限检查通过）/Document object (if permission check passes)/' "$FILE"
sed -i 's/detail="文档不存在"/detail="Document not found"/' "$FILE"
sed -i 's/# 获取文档及其关联的文件夹和应用/# Get document and its associated folder and app/' "$FILE"
sed -i 's/detail="没有权限访问此文档"/detail="No permission to access this document"/' "$FILE"

# === get_document_by_identifier ===
sed -i 's/"""通过标识符（UUID 或路径）获取文档并检查权限/"""Get document by identifier (UUID or path) with permission check/' "$FILE"
sed -i 's/支持两种标识符格式：/Supports two identifier formats:/' "$FILE"
sed -i 's/1. UUID格式: "550e8400-e29b-41d4-a716-446655440000"/1. UUID format: "550e8400-e29b-41d4-a716-446655440000"/' "$FILE"
sed -i 's/2. 路径格式: "\/app_slug\/folder_path\/filename" 或 "\/content\/dam\/..."/2. Path format: "\/app_slug\/folder_path\/filename" or "\/content\/dam\/..."/' "$FILE"
sed -i 's/document_identifier: 文档标识符（UUID字符串或路径）/document_identifier: document identifier (UUID string or path)/' "$FILE"
sed -i 's/# 首先尝试作为UUID解析/# First, try to parse as UUID/' "$FILE"
sed -i 's/# 调用现有的check_document_access函数/# Call existing check_document_access function/' "$FILE"
sed -i 's/# 不是有效的UUID，尝试作为路径处理/# Not a valid UUID, try as path/' "$FILE"
sed -i 's/# 作为路径处理/# Process as path/' "$FILE"
sed -i 's/# 规范化路径：确保以斜杠开头/# Normalize path: ensure leading slash/' "$FILE"
sed -i 's/# 查找文档/# Find document/' "$FILE"
sed -i 's/# 首先尝试通过path字段匹配（新文档系统）/# First try path field match (new system)/' "$FILE"
sed -i 's/# 尝试通过storage_path匹配（相对路径）/# Try storage_path match (relative path)/' "$FILE"
sed -i 's/# 尝试将路径解释为相对于data_root的存储路径/# Try interpreting path relative to data_root/' "$FILE"
sed -i 's/# 路径格式可能是: app_slug\/folder_path\/filename/# Path format: app_slug\/folder_path\/filename/' "$FILE"
sed -i 's/path = path\[1:\]  # 移除开头的斜杠/path = path[1:]  # remove leading slash/' "$FILE"
sed -i 's/# 最后尝试通过组合路径查找（旧系统）/# Last resort: combined path lookup (legacy)/' "$FILE"
sed -i 's/# 路径格式: \/app_slug\/folder_path\/document_filename/# Path format: \/app_slug\/folder_path\/document_filename/' "$FILE"
sed -i 's/# 需要解析出应用slug、文件夹路径和文件名/# Need to parse app slug, folder path, and filename/' "$FILE"
sed -i 's/# 通过应用和文件夹查找/# Find via app and folder/' "$FILE"
sed -i 's/detail=f"文档不存在: {document_identifier}"/detail=f"Document not found: {document_identifier}"/' "$FILE"
sed -i 's/# 检查应用权限（复用check_document_access中的逻辑）/# Check app permission (reuse check_document_access logic)/' "$FILE"

# === get_document_file_path ===
sed -i 's/s 获取文档的实际存储文件路径/s Get the actual storage file path of a document/' "$FILE"
sed -i 's/根据文档的存储信息构建路径：/Build path from document storage info:/' "$FILE"
sed -i 's/1. 优先使用新的路径系统 (storage_path)/1. Use new path system first (storage_path)/' "$FILE"
sed -i 's/2. 如果文档有 full_storage_path，使用设备存储路径/2. If document has full_storage_path, use device storage path/' "$FILE"
sed -i 's/3. 否则，使用默认存储路径/3. Otherwise, use default storage path/' "$FILE"
sed -i 's/4. 兼容旧版本爬虫存储路径 (data\/documents\/)/4. Fallback to legacy crawler path (data\/documents\/)/' "$FILE"
sed -i 's/# 优先使用新的路径系统/# Priority: use new path system/' "$FILE"
sed -i 's/# 构建完整路径/# Build full path/' "$FILE"
sed -i 's/print(f"\[路径系统警告\] 存储路径不存在: /print(f"[Path Warning] Storage path not found: /' "$FILE"
sed -i 's/，回退到旧系统/, falling back to legacy/' "$FILE"
sed -i 's/# 使用旧系统（保持向后兼容）/# Use legacy system (backward compatible)/' "$FILE"
sed -i 's/# 使用设备存储路径/# Use device storage path/' "$FILE"
sed -i 's/# 尝试多个可能的存储位置/# Try multiple possible storage locations/' "$FILE"
sed -i 's/# 默认存储路径/# Default storage path/' "$FILE"
sed -i 's/# 旧版本爬虫存储路径 (data\/documents\/)/# Legacy crawler storage path (data\/documents\/)/' "$FILE"
sed -i 's/# 直接使用 stored_filename（如果它是绝对路径）/# Use stored_filename directly (if absolute path)/' "$FILE"
sed -i 's/# 检查哪个路径存在/# Check which path exists/' "$FILE"
sed -i 's/# 如果没有路径存在，返回默认路径（将导致404错误，但至少会抛出明确的异常）/# If no path exists, return default (will give 404 with explicit error)/' "$FILE"

# === get_document_pdf_path ===
sed -i 's/s 获取文档的PDF文件路径（如果已转换）/s Get the PDF file path of a document (if converted)/' "$FILE"

# === generate_thumbnail ===
sed -i 's/为图像文档生成缩略图并更新元数据/Generate thumbnail for image documents and update metadata/' "$FILE"
sed -i 's/生成100x100 PNG缩略图，存储为base64字符串在document_metadata.original_html中，/Generate 100x100 PNG thumbnail, store as base64 in document_metadata.original_html,/' "$FILE"
sed -i 's/并设置conversion_status为COMPLETED。/and set conversion_status to COMPLETED./' "$FILE"
sed -i 's/参数:/Args:/' "$FILE"
sed -i 's/document: Document对象/document: Document object/' "$FILE"
sed -i 's/settings: 应用配置/settings: application config/' "$FILE"
sed -i 's/返回:/Returns:/' "$FILE"
sed -i 's/bool: 是否成功/bool: whether successful/' "$FILE"
sed -i 's/# 获取文档文件路径/# Get document file path/' "$FILE"
sed -i 's/logging\.error(f"文档文件不存在: /logging.error(f"Document file not found: /' "$FILE"
sed -i 's/# 打开图像文件/# Open image file/' "$FILE"
sed -i 's/# 转换为RGB（如果需要）/# Convert to RGB (if needed)/' "$FILE"
sed -i 's/# 生成100x100缩略图（保持宽高比）/# Generate 100x100 thumbnail (keep aspect ratio)/' "$FILE"
sed -i 's/# 如果图像是RGBA模式，添加白色背景/# If RGBA mode, add white background/' "$FILE"
sed -i 's/background\.paste(img, mask=img\.split()\[-1\])  # 使用alpha通道作为遮罩/background.paste(img, mask=img.split()[-1])  # use alpha channel as mask/' "$FILE"
sed -i 's/# 保存到BytesIO缓冲区（PNG格式）/# Save to BytesIO buffer (PNG format)/' "$FILE"
sed -i 's/# 转换为base64字符串/# Convert to base64 string/' "$FILE"
sed -i 's/# 更新文档元数据/# Update document metadata/' "$FILE"
sed -i 's/# 将base64缩略图存储在original_html字段中（按照老板要求）/# Store base64 thumbnail in original_html field (as requested)/' "$FILE"
sed -i 's/# 同时存储缩略图信息（可选）/# Also store thumbnail info (optional)/' "$FILE"
sed -i 's/# 更新转换状态为已完成/# Update conversion status to completed/' "$FILE"
sed -i 's/# 更新缩略图状态/# Update thumbnail status/' "$FILE"
sed -i 's/# 保存更改到数据库/# Save changes to database/' "$FILE"
sed -i 's/logging\.info(f"为图像文档 {document\.id} 生成缩略图成功")/logging.info(f"Generated thumbnail for image doc {document.id}")/' "$FILE"
sed -i 's/logging\.error(f"生成图像缩略图失败: {str(e)}"/logging.error(f"Failed to generate image thumbnail: {str(e)}"/' "$FILE"
sed -i 's/(exc_info=True)  # 更新错误状态/(exc_info=True)  # Update error status/' "$FILE"

# ============== ROUTE HEADERS AND SECTIONS ==============
sed -i 's/^# ========== Document (文档) 路由 ==========/# ========== Document Routes ==========/' "$FILE"
sed -i 's/^# ========== 文件操作路由 ==========/# ========== File Operation Routes ==========/' "$FILE"
sed -i 's/^# ========== TIFF预览相关路由 ==========/# ========== TIFF Preview Routes ==========/' "$FILE"
sed -i 's/^# ========== 批量操作路由 ==========/# ========== Batch Operation Routes ==========/' "$FILE"

# ============== DOCUMENT LIST ==============
sed -i 's/folder_id: Optional\[uuid\.UUID\] = Query(None, description="按文件夹ID筛选（已弃用，建议使用folder_path）")/folder_id: Optional[uuid.UUID] = Query(None, description="Filter by folder ID (deprecated, use folder_path)")/' "$FILE"
sed -i 's/folder_path: Optional\[str\] = Query(None, description="按文件夹路径筛选，格式: \/app_slug\/folder\/subfolder（推荐）")/folder_path: Optional[str] = Query(None, description="Filter by folder path, format: \/app_slug\/folder\/subfolder (recommended)")/' "$FILE"
sed -i 's/skip: int = Query(0, ge=0, description="跳过记录数")/skip: int = Query(0, ge=0, description="Number of records to skip")/' "$FILE"
sed -i 's/limit: int = Query(100, ge=1, le=1000, description="返回记录数")/limit: int = Query(100, ge=1, le=1000, description="Number of records to return")/' "$FILE"
sed -i 's/status_filter: Optional\[DocumentStatus\] = Query(None, description="按文档状态筛选")/status_filter: Optional[DocumentStatus] = Query(None, description="Filter by document status")/' "$FILE"
sed -i 's/type_filter: Optional\[DocumentType\] = Query(None, description="按文档类型筛选")/type_filter: Optional[DocumentType] = Query(None, description="Filter by document type")/' "$FILE"
sed -i 's/conversion_status_filter: Optional\[ConversionStatus\] = Query(None, description="按转换状态筛选")/conversion_status_filter: Optional[ConversionStatus] = Query(None, description="Filter by conversion status")/' "$FILE"
sed -i 's/search_term: Optional\[str\] = Query(None, description="搜索文档标题或描述")/search_term: Optional[str] = Query(None, description="Search document title or description")/' "$FILE"

sed -i 's/"""获取文档列表（路径优先，兼容UUID）/"""Get document list (path-first, UUID compatible)/' "$FILE"
sed -i 's/支持多种筛选条件：/Supports multiple filters:/' "$FILE"
sed -i 's/- 按文件夹路径筛选（推荐）/- By folder path (recommended)/' "$FILE"
sed -i 's/- 按文件夹ID筛选（已弃用）/- By folder ID (deprecated)/' "$FILE"
sed -i 's/- 按文档状态筛选/- By document status/' "$FILE"
sed -i 's/- 按文档类型筛选/- By document type/' "$FILE"
sed -i 's/- 按转换状态筛选/- By conversion status/' "$FILE"
sed -i 's/- 按标题\/描述搜索/- By title\/description search/' "$FILE"
sed -i 's/注意：建议使用folder_path参数，folder_id参数已弃用/Note: use folder_path parameter, folder_id is deprecated/' "$FILE"
sed -i 's/# 检查参数冲突/# Check parameter conflict/' "$FILE"
sed -i 's/detail="不能同时提供folder_id和folder_path参数"/detail="Cannot provide both folder_id and folder_path parameters"/' "$FILE"
sed -i 's/# 记录警告如果使用folder_id/# Log warning if folder_id used/' "$FILE"
sed -i 's/logger\.warning(f"⚠️  get_documents: 使用已弃用的folder_id参数: /logger.warning(f"get_documents: using deprecated folder_id parameter: /' "$FILE"
sed -i 's/，建议使用folder_path")/", use folder_path instead")/' "$FILE"
sed -i 's/# 构建基础查询/# Build base query/' "$FILE"
sed -i 's/# 注意：使用 selectinload 代替 joinedload 以避免与后续 query.join() 冲突/# Note: use selectinload instead of joinedload to avoid query.join() conflict/' "$FILE"
sed -i 's/# 添加权限筛选：只能查看自己有权限的应用下的文档/# Add permission filter: only docs in user;s accessible apps/' "$FILE"
sed -i "s/# 添加权限筛选：只能查看自己有权限的应用下的文档/# Add permission filter: only docs in user's accessible apps/" "$FILE"
sed -i 's/# 子查询：获取当前用户拥有的所有应用ID/# Subquery: get all app IDs owned by current user/' "$FILE"
sed -i 's/# 通过文件夹→应用链进行筛选（移除抽屉层）/# Filter through folder->app chain (remove drawer layer)/' "$FILE"
sed -i 's/# 应用筛选条件/# Apply filter conditions/' "$FILE"
sed -i 's/# 验证用户是否有权限访问该文件夹/# Verify user has permission to access this folder/' "$FILE"
sed -i 's/# 将UUID转换为字符串进行查询，因为数据库中的folder_id是字符串类型/# Convert UUID to string (DB stores folder_id as string)/' "$FILE"
sed -i 's/# 通过文件夹路径筛选/# Filter by folder path/' "$FILE"
sed -i 's/# 确保路径以斜杠开头/# Ensure path starts with slash/' "$FILE"
sed -i 's/# 文件夹不存在，返回空列表/# Folder not found, return empty list/' "$FILE"
sed -i 's/# 筛选文档/# Filter documents/' "$FILE"
sed -i 's/# 排序和分页/# Sort and paginate/' "$FILE"

# === get_documents_by_folder_path ===
sed -i 's/path: str = Query(\.\.\., description="文件夹路径，格式: \/app_slug\/folder\/subfolder")/path: str = Query(..., description="Folder path, format: \/app_slug\/folder\/subfolder")/' "$FILE"
sed -i 's/"""根据文件夹路径获取文档列表/"""Get document list by folder path/' "$FILE"
sed -i 's/通过文件夹路径获取该路径下的所有文档。/Get all documents under the specified folder path./' "$FILE"
sed -i 's/路径格式: \/app_slug\/folder\/subfolder/Path format: \/app_slug\/folder\/subfolder/' "$FILE"
sed -i 's/detail="路径必须以斜杠开头，格式: \/app_slug\/folder\/subfolder"/detail="Path must start with \/, format: \/app_slug\/folder\/subfolder"/' "$FILE"
sed -i 's/# 通过路径查找文件夹/# Find folder by path/' "$FILE"
sed -i 's/# 如果文件夹不存在，返回空列表（或者可以尝试通过parent_folder_path查找？）/# If folder not found, return empty list (or try parent_folder_path?)/' "$FILE"
sed -i 's/# 对于新系统，我们也可以尝试通过parent_folder_path查找文档/# Could try parent_folder_path lookup for new system/' "$FILE"
sed -i 's/# 但为了安全起见，先检查文件夹是否存在/# For safety, check folder existence first/' "$FILE"
sed -i 's/detail=f"找不到路径对应的文件夹: {path}"/detail=f"No folder found for path: {path}"/' "$FILE"
sed -i 's/# check_folder_access期望UUID，但我们的folder.id是字符串/# check_folder_access expects UUID, but folder.id is a string/' "$FILE"
sed -i 's/# 转换为UUID进行验证/# Convert to UUID for verification/' "$FILE"
sed -i 's/# 如果ID不是有效的UUID，仍然进行基本权限检查/# If ID is not valid UUID, still do basic permission check/' "$FILE"
sed -i 's/# 检查用户是否拥有该应用/# Check if user owns this app/' "$FILE"
sed -i 's/# 现在使用文件夹ID查询文档（重用get_documents的逻辑）/# Now query docs by folder ID (reuse get_documents logic)/' "$FILE"
sed -i 's/# 按文件夹ID筛选/# Filter by folder ID/' "$FILE"

# === get_all_subfolder_documents ===
sed -i 's/folder_path: str = Query(\.\.\., description="文件夹路径，递归查询该路径下所有子孙文件夹的文档")/folder_path: str = Query(..., description="Folder path, recursively query all descendant documents")/' "$FILE"
sed -i 's/"""递归获取文件夹下所有子孙文档（单次DB查询，替代前端BFS+多文档请求）/"""Recursively get all descendant documents (single DB query)/' "$FILE"
sed -i 's/通过文件夹路径找到该路径下的文件夹及其所有子孙文件夹，/Find the folder by path along with all descendant folders,/' "$FILE"
sed -i 's/一次性返回所有文档，避免前端逐个文件夹查询导致的多次API调用。/Return all documents in a single query to avoid multiple API calls./' "$FILE"
sed -i 's/detail="路径必须以斜杠开头"/detail="Path must start with \//"' "$FILE"
sed -i 's/# 查找根文件夹/# Find root folder/' "$FILE"
sed -i 's/# 查询所有子孙文件夹的ID（通过路径前缀匹配实现递归）/# Query all descendant folder IDs (recursive via path prefix)/' "$FILE"
sed -i 's/# 收集所有文件夹ID（含根文件夹自身）/# Collect all folder IDs (including root)/' "$FILE"
sed -i 's/# 一次性查询所有文档/# Query all documents at once/' "$FILE"
sed -i 's/# 按创建时间排序、分页/# Sort by creation time, paginate/' "$FILE"

# === get_document_by_full_path ===
sed -i 's/"""通过完整路径获取文档详情/"""Get document details by full path/' "$FILE"
sed -i 's/路径格式: \/app_slug\/folder_path\/document_filename/Path format: \/app_slug\/folder_path\/document_filename/' "$FILE"
sed -i 's/示例: \/my-app\/marketing\/brochure.pdf/Example: \/my-app\/marketing\/brochure.pdf/' "$FILE"
sed -i 's/支持新旧文档系统：/Supports both new and legacy document systems:/' "$FILE"
sed -i 's/1. 新文档：通过path字段直接匹配/1. New documents: match by path field directly/' "$FILE"
sed -i 's/2. 旧文档：通过文件夹路径和文件名组合查找/2. Legacy docs: match by combining folder path and filename/' "$FILE"
sed -i 's/logger\.info(f"通过路径获取文档详情: /logger.info(f"Get document details by path: /' "$FILE"
sed -i 's/# 方法1：首先尝试通过path字段直接匹配（新文档系统，路径如 \/content\/dam\/...）/# Method 1: Try direct path field match first (new system, path like \/content\/dam\/...)/' "$FILE"
sed -i 's/logger\.info(f"通过path字段找到文档: /logger.info(f"Found document by path field: /' "$FILE"
sed -i 's/# 方法1.5：尝试通过旧前缀的path字段匹配（兼容旧数据）/# Method 1.5: Try legacy prefix path field match (backward compat)/' "$FILE"
sed -i 's/# 新格式: \/boarding\/canadasite\/... (无前缀)/# New format: \/boarding\/canadasite\/... (no prefix)/' "$FILE"
sed -i 's/# 旧格式1: \/content\/boarding\/.../# Legacy format 1: \/content\/boarding\/.../' "$FILE"
sed -i 's/# 旧格式2: \/content\/dam\/boarding\/.../# Legacy format 2: \/content\/dam\/boarding\/.../' "$FILE"
sed -i 's/logger\.info(f"通过{prefix} path字段找到文档: /logger.info(f"Found document via {prefix} path field: /' "$FILE"
sed -i 's/# 方法2：尝试通过storage_path字段匹配/# Method 2: Try storage_path match/' "$FILE"
sed -i 's/# storage_path 存储时不带头斜杠(如 "boarding\/canadasite\/...")/# storage_path stored without leading slash (e.g. "boarding\/canadasite\/...")/' "$FILE"
sed -i 's/# 所以同时尝试带\/和不带\/两种格式/# Try both with and without leading slash/' "$FILE"
sed -i 's/# 去掉开头的斜杠再试一次/# Remove leading slash and try again/' "$FILE"
sed -i 's/logger\.info(f"通过storage_path字段找到文档: /logger.info(f"Found document by storage_path: /' "$FILE"
sed -i 's/# 检查访问权限/# Check access permission/' "$FILE"
sed -i 's/# 方法3：解析路径为应用slug、文件夹路径和文件名/# Method 3: Parse path into app slug, folder path, filename/' "$FILE"
sed -i 's/detail="路径格式无效，至少需要应用slug和文件名"/detail="Invalid path format, need at least app slug and filename"/' "$FILE"
sed -i 's/folder_path_parts = path_parts\[1:-1\]  # 中间部分为文件夹路径/folder_path_parts = path_parts[1:-1]  # middle part is folder path/' "$FILE"
sed -i 's/logger\.info(f"解析路径: app_slug={app_slug}, folder_path={folder_path}, filename={filename}")/logger.info(f"Parsed path: app_slug={app_slug}, folder_path={folder_path}, filename={filename}")/' "$FILE"
sed -i 's/detail=f"应用不存在: {app_slug}"/detail=f"App not found: {app_slug}"/' "$FILE"
sed -i 's/detail=f"文件夹不存在: {folder_path}"/detail=f"Folder not found: {folder_path}"/' "$FILE"
sed -i 's/# 尝试使用父文件夹路径/# Try using parent folder path/' "$FILE"
sed -i 's/# 安全化文件名比较/# Sanitize filename matching/' "$FILE"
sed -i 's/# 查找文档（通过存储文件名）/# Find document (by stored filename)/' "$FILE"
sed -i 's/# 尝试通过原始文件名查找/# Try by original filename/' "$FILE"
sed -i 's/detail=f"文档不存在: {filename} (路径: {path})"/detail=f"Document not found: {filename} (path: {path})"/' "$FILE"
sed -i 's/logger\.info(f"通过文件夹和文件名找到文档: /logger.info(f"Found document by folder and filename: /' "$FILE"

# === Page routes ===
sed -i 's/"""通过标识符（UUID 或路径）获取文档的所有页面"""/"""Get all pages of a document by identifier (UUID or path)"""/' "$FILE"
sed -i 's/# 先验证文档访问权限并获取文档对象/# First verify document access and get object/' "$FILE"
sed -i 's/# 获取页面列表/# Get page list/' "$FILE"
sed -i 's/"""通过标识符（UUID 或路径）获取文档的特定页面"""/"""Get a specific page of a document by identifier (UUID or path)"""/' "$FILE"
sed -i 's/# 获取页面/# Get page/' "$FILE"
sed -i 's/detail="页面不存在或不属于此文档"/detail="Page not found or does not belong to this document"/' "$FILE"
sed -i 's/"""通过标识符（UUID 或路径）更新页面信息（主要用于更新索引字段）"""/"""Update page info by identifier (UUID or path) - mainly for index fields"""/' "$FILE"
sed -i 's/# 如果修改了页码，检查是否与其他页面冲突/# If page number changed, check for conflicts/' "$FILE"
sed -i 's/detail="此文档中已存在该页码的页面"/detail="A page with this number already exists for this document"/' "$FILE"
sed -i 's/# 更新字段/# Update fields/' "$FILE"
sed -i 's/# 更新审计字段/# Update audit fields/' "$FILE"
sed -i 's/"""通过标识符（UUID 或路径）删除页面"""/"""Delete a page by identifier (UUID or path)"""/' "$FILE"
sed -i 's/return {"message": "页面删除成功"}/return {"message": "Page deleted successfully"}/' "$FILE"

# ============== UPLOAD ==============
sed -i 's/folder_path: Optional\[str\] = Form(None, description="文件夹路径，格式: \/app_slug\/folder\/subfolder（推荐）")/folder_path: Optional[str] = Form(None, description="Folder path, format: \/app_slug\/folder\/subfolder (recommended)")/' "$FILE"
sed -i 's/folder_id: Optional\[uuid\.UUID\] = Form(None, description="文件夹ID（已弃用，建议使用folder_path）")/folder_id: Optional[uuid.UUID] = Form(None, description="Folder ID (deprecated, use folder_path)")/' "$FILE"
sed -i 's/"""上传文档文件（路径优先，兼容UUID）/"""Upload a document file (path-first, UUID compatible)/' "$FILE"
sed -i 's/注意：这里只保存文件基本信息，实际的文件处理和转换通过异步任务完成/Note: only saves basic file info, actual processing is done asynchronously/' "$FILE"
sed -i 's/如果提供了 naming_rule_id，将使用文件命名规则生成文档编号（document_number）/If naming_rule_id provided, generates document_number using naming rules/' "$FILE"
sed -i 's/文档编号格式：{basename}{序列号}，如"PO-1001"/Doc number format: {basename}{sequence}, e.g. "PO-1001"/' "$FILE"
sed -i 's/系统存储的文件名使用UUID确保唯一性，用户不关心系统文件名/System stores files with UUID filenames for uniqueness/' "$FILE"
sed -i 's/如果命名规则包含 subfolder_name 或提供了 device_id，文件将存储到设备的子文件夹中/If naming rule has subfolder_name or device_id, files go to device subfolders/' "$FILE"
sed -i 's/实现文件按类型分目录存储，避免所有文件堆在同一个目录/Store files in type-specific subdirectories to keep them organized/' "$FILE"
sed -i 's/支持通过文件夹路径（推荐）或文件夹ID（已弃用）指定目标文件夹。/Supports target folder by path (recommended) or ID (deprecated)./' "$FILE"
sed -i 's/print(f"\[DEBUG\] upload_document 接收到请求:")/print(f"[DEBUG] upload_document received request:")/' "$FILE"
sed -i 's/print(f"\[DEBUG\] 接收到请求参数:")/print(f"[DEBUG] Received request params:")/' "$FILE"
sed -i 's/# 检查至少提供了一个文件夹标识符/# Check at least one folder identifier provided/' "$FILE"
sed -i 's/detail="必须提供folder_path（推荐）或folder_id参数"/detail="Must provide folder_path (recommended) or folder_id parameter"/' "$FILE"
sed -i 's/# 记录警告如果使用folder_id/# Log warning if using folder_id/' "$FILE"
sed -i 's/logger\.warning(f"⚠️  upload_document: 使用已弃用的folder_id参数: /logger.warning(f"upload_document: using deprecated folder_id: /' "$FILE"
sed -i 's/# 获取文件夹（路径优先）/# Get folder (path-first)/' "$FILE"
sed -i 's/# 使用路径查找文件夹，如果不存在则自动创建/# Find folder by path, auto-create if not found/' "$FILE"
sed -i 's/print(f"\[DEBUG\] 文件夹解析结果: folder_path=/print(f"[DEBUG] Folder parse result: folder_path=/' "$FILE"
sed -i 's/→ folder\.path=/ -> folder.path=/' "$FILE"
sed -i 's/→ folder\.id={folder\.id}}/ -> folder.id={folder.id}}/' "$FILE"
sed -i 's/logger\.info(f"✅ upload_document: 通过路径找到文件夹: /logger.info(f"upload_document: found folder by path: /' "$FILE"
sed -i 's/# 确保folder_id指向实际文件夹的ID（修复用folder_path时folder_id=None的bug）/# Ensure folder_id points to actual folder ID (fix folder_path with folder_id=None bug)/' "$FILE"
sed -i 's/# 使用ID查找文件夹（向后兼容）/# Find folder by ID (backward compat)/' "$FILE"
sed -i 's/print(f"\[DEBUG\] 文件夹解析结果: folder_id=/print(f"[DEBUG] Folder parse result: folder_id=/' "$FILE"
sed -i 's/→ folder\.path={folder\.path!r}}/ -> folder.path={folder.path!r}}/' "$FILE"
sed -i 's/logger\.warning(f"⚠️  upload_document: 通过UUID找到文件夹: /logger.warning(f"upload_document: found folder by UUID: /' "$FILE"
sed -i 's/(路径: {folder\.path})/(path: {folder.path})/' "$FILE"

# Naming rule comments
sed -i 's/# 如果提供了命名规则ID，验证规则并获取下一个文档编号/# If naming_rule_id provided, validate and get next doc number/' "$FILE"
sed -i 's/# 获取命名规则/# Get naming rule/' "$FILE"
sed -i 's/detail="命名规则不存在"/detail="Naming rule not found"/' "$FILE"
sed -i 's/# 验证命名规则属于同一个应用/# Verify naming rule belongs to same app/' "$FILE"
sed -i 's/# 通过文件夹→应用链找到应用ID/# Find app ID through folder->app chain/' "$FILE"
sed -i 's/detail="命名规则不属于当前应用"/detail="Naming rule does not belong to this app"/' "$FILE"
sed -i 's/# 生成文档编号（如"PO-1001"）/# Generate document number (e.g. "PO-1001")/' "$FILE"
sed -i 's/# 递增序列号/# Increment sequence number/' "$FILE"
sed -i 's/# 检查文件大小（限制为100MB）/# Check file size (max 100MB)/' "$FILE"
sed -i 's/detail="文件大小不能超过100MB"/detail="File size cannot exceed 100MB"/' "$FILE"
sed -i 's/# 保存到临时文件/# Save to temp file/' "$FILE"
sed -i 's/# 🐛 修复: file.filename 可能包含路径分隔符（如 wet-boew\/assets\/...\/file.png），/# 🐛 Fix: file.filename may contain path separators (e.g. wet-boew\/assets\/...\/file.png),/' "$FILE"
sed -i 's/# 使用 Path().name 仅取文件名部分，避免创建不存在的子目录/# Use Path().name to extract just the filename, avoid creating subdirs/' "$FILE"
sed -i 's/# 确定文件类型和扩展名/# Determine file type and extension/' "$FILE"
sed -i 's/# 映射扩展名到FileType枚举/# Map extension to FileType enum/' "$FILE"
sed -i 's/# 去掉扩展名前的点/# Remove leading dot from extension/' "$FILE"
sed -i 's/# 确定MIME类型/# Determine MIME type/' "$FILE"
sed -i 's/# 优先使用上传时声明的 Content-Type；如果为 octet-stream 则根据扩展名推断/# Use declared Content-Type first; infer from extension if octet-stream/' "$FILE"
sed -i 's/# 确定最终显示的文件名/# Determine display filename/' "$FILE"
sed -i 's/# original_filename 保持用户上传的原始文件名/# Keep original uploaded filename/' "$FILE"
sed -i 's/# stored_filename将在generate_storage_paths调用后设置为safe_filename/# stored_filename will be set to safe_filename after generate_storage_paths/' "$FILE"
sed -i 's/# 不再使用UUID作为文件名，采用纯path结构/# No longer use UUID for filenames, use pure path structure/' "$FILE"
sed -i 's/# 如果使用命名规则，生成文档编号（document_number）/# If using naming rules, generate document_number/' "$FILE"
sed -i 's/# 使用命名规则生成文档编号（如"PO-1001"）/# Generate document_number from naming rules (e.g. "PO-1001")/' "$FILE"
sed -i 's/# ========== 设备选择和存储路径确定 ==========/# ========== Device Selection and Storage Path ==========/' "$FILE"
sed -i 's/# ========== 设备选择和存储路径确定结束 ==========/# ========== End Device Selection and Storage Path ==========/' "$FILE"
sed -i 's/# ========== 路径系统重构：生成存储路径和URL路径 ==========/# ========== Path System: Generate Storage and URL Paths ==========/' "$FILE"
sed -i 's/# ========== 路径系统重构结束 ==========/# ========== End Path System ==========/' "$FILE"
sed -i 's/# ========== 路径系统重构：文件存储 ==========/# ========== Path System: File Storage ==========/' "$FILE"

# Device selection comments
sed -i 's/# 计算文件大小（MB）/# Calculate file size (MB)/' "$FILE" 2>/dev/null || true
sed -i 's/# 情况1：指定了device_id/# Case 1: device_id specified/' "$FILE"
sed -i 's/# 情况2：使用命名规则，且规则指定了subfolder_name，自动选择设备/# Case 2: naming rule with subfolder_name, auto-select device/' "$FILE"
sed -i 's/# 获取所有活跃的存储设备/# Get all active storage devices/' "$FILE"
sed -i 's/# 只使用主存储设备/# Only use primary storage devices/' "$FILE"
sed -i 's/# 选择最佳设备/# Select best device/' "$FILE"
sed -i 's/# 使用命名规则的子文件夹名称/# Use naming rule subfolder name/' "$FILE"
sed -i 's/# 情况3：使用默认存储（不指定设备）/# Case 3: Use default storage (no device specified)/' "$FILE"
sed -i 's/# 如果选择了设备，确定存储路径/# If device selected, determine storage path/' "$FILE"
sed -i 's/# 确保设备路径存在/# Ensure device path exists/' "$FILE"
sed -i 's/# 确定子文件夹路径/# Determine subfolder path/' "$FILE"
sed -i 's/# 默认子文件夹/# Default subfolder/' "$FILE"
sed -i 's/# 构建完整存储路径/# Build full storage path/' "$FILE"
sed -i 's/# 创建子文件夹（如果不存在）/# Create subfolder (if not exists)/' "$FILE"

# more path system
sed -i 's/# Get app信息（通过文件夹）/# Get app info (via folder)/' "$FILE"
sed -i 's/# 生成存储路径和URL路径/# Generate storage and URL paths/' "$FILE"
sed -i 's/# 确保目录存在/# Ensure directory exists/' "$FILE"
sed -i 's/# 计算相对存储路径（相对于DATA_ROOT）/# Calculate relative storage path (relative to DATA_ROOT)/' "$FILE"
sed -i 's/# 如果路径不在data_root下，使用绝对路径/# If path outside data_root, use absolute path/' "$FILE"
sed -i 's/# 设置存储文件名为安全文件名（纯path结构，不使用UUID）/# Set stored filename to safe filename (pure path, no UUID)/' "$FILE"
sed -i 's/# 制作一个URL路径的副本（用于document_metadata.url）//# Create URL path copy (for document_metadata.url)/' "$FILE"
sed -i 's/# 创建文档记录 - 确保所有UUID都转换为字符串/# Create document record - ensure all UUIDs converted to string/' "$FILE"
sed -i 's/# 文档信息/# Document info/' "$FILE"
sed -i 's/# 文件信息/# File info/' "$FILE"
sed -i 's/# 存储设备信息/# Storage device info/' "$FILE"
sed -i 's/# 路径系统字段/# Path system fields/' "$FILE"
sed -i 's/# 转换状态/# Conversion status/' "$FILE"
sed -i 's/# 审计字段/# Audit fields/' "$FILE"
sed -i 's/# 如果使用了命名规则，保存规则更新/# If naming rules used, save rule update/' "$FILE"
sed -i 's/# 使用新路径系统存储文件/# Store file using new path system/' "$FILE"
sed -i 's/# 回滚事务（删除文档记录）/# Rollback transaction (delete document record)/' "$FILE"
sed -i 's/# 保存设备容量更新/# Save device capacity update/' "$FILE"
sed -i 's/# 移动文件到新路径/# Move file to new path/' "$FILE"
sed -i 's/# 验证文件已移动/# Verify file was moved/' "$FILE"

# Image handling comments
sed -i 's/# 定义支持的图像文件类型/# Define supported image file types/' "$FILE"
sed -i 's/# 如果是图像文件，直接生成缩略图并标记为已完成/# If image file, generate thumbnail and mark complete/' "$FILE"
sed -i 's/# 图像文件不需要PDF转换任务/# Image files do not need PDF conversion task/' "$FILE"
sed -i 's/# 如果缩略图生成失败，仍创建PDF转换任务作为后备/# If thumbnail fails, still create PDF conversion task as fallback/' "$FILE"
sed -i 's/# 非图像文件，创建PDF转换任务/# Non-image files, create PDF conversion task/' "$FILE"
sed -i 's/# 准备响应数据/# Prepare response data/' "$FILE"
sed -i 's/# 如果使用命名规则生成的文档编号/# If document number generated via naming rules/' "$FILE"
sed -i 's/# 路径系统信息/# Path system info/' "$FILE"
sed -i 's/print(f"\[路径系统\] 生成的路径:")/print(f"[Path System] Generated paths:")/' "$FILE"
sed -i 's/print(f"\(存储路径: {storage_path}\)")/print(f"(Storage path: {storage_path})")/' "$FILE"
sed -i 's/print(f"\(URL路径: {url_path}\)")/print(f"(URL path: {url_path})")/' "$FILE"
sed -i 's/print(f"\(安全文件名: {safe_filename}\)")/print(f"(Safe filename: {safe_filename})")/' "$FILE"
sed -i 's/print(f"  存储路径: {storage_path}")/print(f"  Storage path: {storage_path}")/' "$FILE"
sed -i 's/print(f"  URL路径: {url_path}")/print(f"  URL path: {url_path}")/' "$FILE"
sed -i 's/print(f"  安全文件名: {safe_filename}")/print(f"  Safe filename: {safe_filename}")/' "$FILE"
sed -i 's/print(f"  存储文件名: {stored_filename}")/print(f"  Stored filename: {stored_filename}")/' "$FILE"

# Prints in upload
sed -i 's/print(f"\[路径系统\] 移动文件到: /print(f"[Path System] Moving file to: /' "$FILE"
sed -i 's/print(f"\[路径系统\] 文件移动成功，大小: /print(f"[Path System] File moved successfully, size: /' "$FILE"
sed -i 's/print(f"\[图像处理\] 检测到图像文件: /print(f"[Image] Detected image file: /' "$FILE"
sed -i 's/print(f"\[图像处理\] 缩略图生成成功，/print(f"[Image] Thumbnail generated successfully, /' "$FILE"
sed -i 's/print(f"\[图像处理\] 缩略图生成失败，但仍创建PDF转换任务"/print(f"[Image] Thumbnail gen failed, will create PDF conversion task"/' "$FILE"

echo "Sed translation complete!"
echo ""
echo "=== Verifying syntax ==="
cd /home/hongb/.openclaw/workspace/filebot/backend
python3 -m py_compile app/routers/documents.py 2>&1 && echo "✅ No syntax errors" || echo "❌ Syntax error"

echo ""
echo "=== Checking for remaining Chinese ==="
python3 -c "
import re
with open('app/routers/documents.py') as f:
    content = f.read()
remaining = len(re.findall(r'[\u4e00-\u9fff\u3400-\u4dbf\uf900-\ufaff]', content))
print(f'Remaining Chinese chars: {remaining}')
if remaining > 0:
    for i, line in enumerate(content.split(chr(10)), 1):
        if re.search(r'[\u4e00-\u9fff]', line):
            print(f'  L{i}: {line.strip()[:120]}')
else:
    print('🎉 ALL CHINESE TRANSLATED!')
"