"""
AI-assisted functionality routes
"""

from fastapi import APIRouter, HTTPException, BackgroundTasks
import sqlite3
import uuid
import os
from datetime import datetime
from typing import List

from app.models import (
    AIRequest, AIResponse, AITaskCreate, AITaskResponse, 
    TaskType, TaskStatus, PageCreate, PageUpdate
)

router = APIRouter(prefix="/api/v1/ai", tags=["ai"])

WEBBOT_DB_PATH = os.environ.get(
    "WEBBOT_DB_PATH",
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "webbot.db")
)

def get_db_connection():
    """Get WebBot database connection"""
    try:
        conn = sqlite3.connect(WEBBOT_DB_PATH)
        conn.row_factory = sqlite3.Row
        return conn
    except sqlite3.Error as e:
        raise HTTPException(status_code=500, detail=f"Database connection failed: {e}")

# 模拟AI服务
class MockAIService:
    """Mock AI service for demonstration"""
    
    @staticmethod
    def create_page(description: str) -> str:
        """Mock AI page creation"""
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{description[:50]}</title>
    <style>
        body {{ font-family: Arial, sans-serif; line-height: 1.6; margin: 20px; }}
        h1 {{ color: #333; }}
        p {{ color: #666; }}
    </style>
</head>
<body>
    <h1>{description}</h1>
    <p>This page was generated by AI based on the description: "{description}"</p>
    <p>The content includes proper HTML structure, semantic elements, and basic styling.</p>
    <h2>Key Sections</h2>
    <ul>
        <li>Introduction and overview</li>
        <li>Main content areas</li>
        <li>Contact information</li>
        <li>Related links</li>
    </ul>
    <p>All content follows Canada.ca accessibility guidelines and web standards.</p>
</body>
</html>"""
    
    @staticmethod
    def optimize_content(content: str) -> str:
        """Mock AI content optimization"""
        # 简单的优化：Add标题、格式化段落
        optimized = content.replace('\n\n', '</p><p>')
        if not optimized.startswith('<h1>'):
            optimized = f"<h1>Optimized Content</h1>\n<p>{optimized}</p>"
        return optimized
    
    @staticmethod
    def review_content(content: str) -> str:
        """Mock AI content review"""
        # 简单的合规检查
        issues = []
        
        if len(content) < 100:
            issues.append("Content is too short. Consider adding more detail.")
        
        if 'http://' in content and 'https://' not in content:
            issues.append("Consider using HTTPS for security.")
        
        if not any(word in content.lower() for word in ['contact', 'email', 'phone']):
            issues.append("Consider adding contact information.")
        
        if issues:
            return f"Review completed. Issues found:\n- " + "\n- ".join(issues)
        else:
            return "Review completed. Content meets basic Canada.ca standards."
    
    @staticmethod
    def suggest_deletion(page_info: dict) -> str:
        """Mock AI deletion suggestions"""
        return f"AI suggests reviewing this page for potential deletion. Reason: The page '{page_info.get('title', 'Unknown')}' may be outdated or have low traffic. Consider updating or archiving instead of deletion."

# 模拟AITask处理
async def process_ai_task(task_id: str, task_type: str, prompt: str):
    """Background AI task processing"""
    conn = get_db_connection()
    cursor = conn.cursor()
    
    try:
        # 更NewTaskStatus为处理中
        cursor.execute(
            "UPDATE webbot_tasks SET status = ?, started_at = ? WHERE id = ?",
            (TaskStatus.PROCESSING.value, datetime.now().isoformat(), task_id)
        )
        conn.commit()
        
        # 模拟AI处理
        import time
        time.sleep(2)  # 模拟处理时间
        
        ai_service = MockAIService()
        result = ""
        
        if task_type == TaskType.CREATE_PAGE.value:
            result = ai_service.create_page(prompt)
        elif task_type == TaskType.OPTIMIZE_PAGE.value:
            result = ai_service.optimize_content(prompt)
        elif task_type == TaskType.REVIEW_PAGE.value:
            result = ai_service.review_content(prompt)
        elif task_type == TaskType.DELETE_PAGE.value:
            result = ai_service.suggest_deletion({"title": prompt})
        
        # 更NewTask为完成
        cursor.execute(
            "UPDATE webbot_tasks SET status = ?, result = ?, completed_at = ? WHERE id = ?",
            (TaskStatus.COMPLETED.value, result, datetime.now().isoformat(), task_id)
        )
        conn.commit()
        
    except Exception as e:
        # 更NewTask为失败
        cursor.execute(
            "UPDATE webbot_tasks SET status = ?, error_message = ? WHERE id = ?",
            (TaskStatus.FAILED.value, str(e), task_id)
        )
        conn.commit()
        raise
    finally:
        conn.close()

@router.post("/create-task", response_model=AITaskResponse)
async def create_ai_task(task: AITaskCreate, background_tasks: BackgroundTasks):
    """Create AI task"""
    conn = get_db_connection()
    cursor = conn.cursor()
    
    try:
        task_id = f"task-{uuid.uuid4().hex[:12]}"
        now = datetime.now().isoformat()
        
        # 插入Task
        cursor.execute("""
            INSERT INTO webbot_tasks 
            (id, task_type, page_id, description, ai_model, prompt, status, created_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        """, (
            task_id,
            task.task_type.value,
            task.page_id,
            task.description,
            task.ai_model or "mock-ai-v1",
            task.prompt,
            TaskStatus.PENDING.value,
            now
        ))
        
        conn.commit()
        
        # 启动后台Task处理
        background_tasks.add_task(
            process_ai_task, 
            task_id, 
            task.task_type.value, 
            task.prompt
        )
        
        # 获取创建的Task
        cursor.execute("SELECT * FROM webbot_tasks WHERE id = ?", (task_id,))
        created_task = cursor.fetchone()
        
        return AITaskResponse(**dict(created_task))
        
    except sqlite3.Error as e:
        conn.rollback()
        raise HTTPException(status_code=500, detail=f"Failed to create task: {e}")
    finally:
        conn.close()

@router.get("/tasks", response_model=List[AITaskResponse])
async def list_tasks(skip: int = 0, limit: int = 50):
    """Get AI task list"""
    conn = get_db_connection()
    cursor = conn.cursor()
    
    try:
        cursor.execute("""
            SELECT * FROM webbot_tasks 
            ORDER BY created_at DESC 
            LIMIT ? OFFSET ?
        """, (limit, skip))
        
        tasks = cursor.fetchall()
        return [AITaskResponse(**dict(task)) for task in tasks]
        
    except sqlite3.Error as e:
        raise HTTPException(status_code=500, detail=f"Query failed: {e}")
    finally:
        conn.close()

@router.get("/tasks/{task_id}", response_model=AITaskResponse)
async def get_task(task_id: str):
    """Get AI task details"""
    conn = get_db_connection()
    cursor = conn.cursor()
    
    try:
        cursor.execute("SELECT * FROM webbot_tasks WHERE id = ?", (task_id,))
        task = cursor.fetchone()
        
        if not task:
            raise HTTPException(status_code=404, detail="Task未找到")
        
        return AITaskResponse(**dict(task))
        
    except sqlite3.Error as e:
        raise HTTPException(status_code=500, detail=f"Query failed: {e}")
    finally:
        conn.close()

@router.post("/create-page", response_model=AIResponse)
async def ai_create_page(request: AIRequest):
    """AI-assisted page creation"""
    ai_service = MockAIService()
    
    try:
        if request.action != TaskType.CREATE_PAGE:
            return AIResponse(
                success=False,
                error=f"Invalid action for this endpoint. Use {TaskType.CREATE_PAGE.value}"
            )
        
        result = ai_service.create_page(request.content)
        
        return AIResponse(
            success=True,
            result=result,
            processing_time=1.5
        )
        
    except Exception as e:
        return AIResponse(
            success=False,
            error=str(e)
        )

@router.post("/optimize-page", response_model=AIResponse)
async def ai_optimize_page(request: AIRequest):
    """AI-assisted page optimization"""
    ai_service = MockAIService()
    
    try:
        if request.action != TaskType.OPTIMIZE_PAGE:
            return AIResponse(
                success=False,
                error=f"Invalid action for this endpoint. Use {TaskType.OPTIMIZE_PAGE.value}"
            )
        
        result = ai_service.optimize_content(request.content)
        
        return AIResponse(
            success=True,
            result=result,
            processing_time=1.0
        )
        
    except Exception as e:
        return AIResponse(
            success=False,
            error=str(e)
        )

@router.post("/review-page", response_model=AIResponse)
async def ai_review_page(request: AIRequest):
    """AI-assisted page review"""
    ai_service = MockAIService()
    
    try:
        if request.action != TaskType.REVIEW_PAGE:
            return AIResponse(
                success=False,
                error=f"Invalid action for this endpoint. Use {TaskType.REVIEW_PAGE.value}"
            )
        
        result = ai_service.review_content(request.content)
        
        return AIResponse(
            success=True,
            result=result,
            processing_time=0.8
        )
        
    except Exception as e:
        return AIResponse(
            success=False,
            error=str(e)
        )

@router.post("/suggest-deletion", response_model=AIResponse)
async def ai_suggest_deletion(request: AIRequest):
    """AI-assisted deletion suggestions"""
    ai_service = MockAIService()
    
    try:
        if request.action != TaskType.DELETE_PAGE:
            return AIResponse(
                success=False,
                error=f"Invalid action for this endpoint. Use {TaskType.DELETE_PAGE.value}"
            )
        
        # 假设content包含pageInformation
        result = ai_service.suggest_deletion(request.context or {})
        
        return AIResponse(
            success=True,
            result=result,
            processing_time=0.5
        )
        
    except Exception as e:
        return AIResponse(
            success=False,
            error=str(e)
        )